### ISSUE TITLE
Title Shrinking

### ISSUE THREAD

**Issue by oddsoul** [t04glovern/t04glovern.github.io#1]
Having issues with the website constantly shrinking the Title rather than making it disappear. 

I find this completely distracting and also takes up valuable real-estate for more content that i'm sure will be added to your site in the near future.

If you could please try to resolve this, that would be great

**Comment by t04glovern** [comment]
The upstream source I use for this blog fixed this problem. It will now slowly ascend/descend making it a lot easier on the eyes
