### ISSUE TITLE
No Music at 404 page

### ISSUE THREAD

**Issue by oddsoul** [t04glovern/t04glovern.github.io#2]
Please resolve this issue as I love your work and would still like to be entertained while your site is down

**Comment by oddsoul** [comment]
https://thebest404pageever.com/ Something like this would be awesome

**Comment by t04glovern** [comment]
I suppose the purpose of a 404 page is to only occur when something goes wrong. As much as I like the idea of having a mattress store commercial on the page, I don't think it's important enough at present
